name = "life-tracker"
main = "src/index.tsx"
compatibility_date = "2023-09-18"

[site]
bucket = "./assets"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "life-tracker"
database_id = "5f6e7ae7-32da-409c-b179-6365d4d4eb43"
