name = "d1-tutorial"
main = "src/index.tsx"
compatibility_date = "2023-09-18"

[site]
bucket = "./assets"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "hello-world"
database_id = "4d478301-53a8-45c3-afc4-e5b41a8831d5"

